### PR TITLE
Adding a class to <mark> tags to facilitate styling (only for ranges)

### PR DESCRIPTION
**Pull request by olance**
This PR adds the possibility to set a `class` property in ranges objects, that will be set on the generated `<mark>` tags so that it is easier to style different marks.

### CODE REVIEW

**Comment by olance** [comment]
that was quick :)

**Comment by mistic100** [comment]
could you do the same for words ?

**Comment by olance** [comment]
I've had a quick look but it's going to need a bit more work, as you only store words in an array in the end, if I am not mistaken, so it's not as easy as putting a new property in the "cleaned" words objects.

But I can try! ^^

**Comment by mistic100** [comment]
In `Utilities.cleanWords`

Instead of
```js
out = {
  'red': ['word1', 'word2']
};
```

it could be 
```js
out = [
  {
    color: 'red',
    word: ['word1', 'word2']
  }
];
```

it's more consistent with the cleaned ranges list

yes I admit it's a bit more refactoring

**Comment by olance** [comment]
Okay that's a start, I'll have a look :)
And I'll update the README maybe? ^^

**Comment by mistic100** [comment]
not the readme, the `gh-pages` branch

**Comment by olance** [comment]
Okay

**Pull request merged**
